version: '3.9'
services:
  db:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cat
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    image: node:alpine
    depends_on:
      - db
    ports:
      - '32000:80'

volumes:
  pgdata:
